import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Sidebar from '../components/Sidebar';
export default function Home() {
  const [enableBell, setEnableBell] = useState(false);
  // const [menus, setMenus] = useState('home');
  return (
    <div className='h-screen w-full flex flex-col background-color px-10 font-sans'>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* navbar */}
      <div className='w-full flex flex-row justify-between px-5 py-3'>
        <span>
          <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </span>
        <div className='w-1/3 flex flex-row justify-end pr-10'>
          <button className='flex flex-row items-center py-1 px-2 cursor-pointer'>
            <Image
              src={enableBell ? '/bell_on_icon.svg' : '/bell_off_icon.svg'}
              alt='Bell icon'
              width={24}
              height={24}
              onClick={() => setEnableBell(!enableBell)}
            />
          </button>

          <div className='h-8 border-r-2 border-black mx-3'></div>
          <button className='flex flex-row items-center py-1 pl-3 pr-10'>
            <Image
              src='/settings_icon.svg'
              alt='Login icon'
              width={24}
              height={24}
            />
            <div className='h-8 w-8 flex overflow-hidden rounded-full ml-6'>
              <Image
                src='/me_avatar.jpg'
                alt='avatar icon'
                width={500}
                height={617}
              />
            </div>

            <p className='ml-2 text-lg font-bold'>Fariz Akbar</p>
          </button>
        </div>
      </div>
      {/* navbar end */}
      {/* card */}

      <main className='w-full h-full  mt-5 mb-10 p-3 flex flex-row'>
        {/* sidebar */}
        <Sidebar />
        {/* sidebar end */}
        {/* main content */}
        <div className='flex flex-row h-full sm:w-7/12 md:w-8/12 lg:w-9/12 xl:w-10/12 bg-yellow-200'>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum
          aliquid quaerat provident blanditiis quidem magnam earum inventore in
          labore minus? Dolor, earum ab vero saepe ducimus amet libero vel neque
          facilis aut at, nihil commodi illo eum. Asperiores labore perferendis
          dolores blanditiis dolorem quae ut modi cupiditate natus, at ab
          ratione inventore doloribus architecto, obcaecati nostrum expedita
          repellendus. Et perferendis aliquid nostrum nulla repudiandae eaque
          sequi, deserunt labore dolores? Libero maxime accusantium dolorem,
          officiis doloremque quae perferendis, veritatis illo voluptate
          obcaecati, odio voluptatum molestiae? Suscipit officia sed consectetur
          quidem, earum aspernatur quia et ut ipsam adipisci repellat doloribus
          expedita ullam?
        </div>
        {/* main content end */}
      </main>
      {/* card end */}
    </div>
  );
}
