import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import Sidebar from '../components/Sidebar';

const MyActivity = () => {
  const [enableBell, setEnableBell] = useState(false);
  // const [menus, setMenus] = useState('home');
  const [todos, setTodos] = useState([
    { id: 1, text: 'Learn Next.js' },
    { id: 2, text: 'Learn Next.js' },
    { id: 3, text: 'Learn Next.js' },
    { id: 4, text: 'Learn Next.js' },
    { id: 5, text: 'Learn Next.js' },
    { id: 6, text: 'Learn Next.js' },
    { id: 7, text: 'Learn Next.js' },
    { id: 8, text: 'Learn Next.js' },
    { id: 9, text: 'Learn Next.js' },
    { id: 10, text: 'Learn Next.js' },
    { id: 11, text: 'Learn Next.js' },
    { id: 12, text: 'Learn Next.js' },
    { id: 13, text: 'Learn Next.js' },
    { id: 14, text: 'Learn Next.js' },
  ]);
  // const [showTodoMenu, setShowTodoMenu] = useState(false);
  const [selectedTodo, setSelectedTodo] = useState({
    todoId: 0,
    menuOpen: false,
  });
  return (
    <div className='h-screen w-full flex flex-col background-color md:px-10 font-sans overflow-y-scroll scrollbar'>
      <Head>
        {/* <html lang='en' /> */}
        <title>My Activity</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* navbar */}
      <div className='w-full flex flex-row justify-between px-5 py-3'>
        <span>
          <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </span>
        <div className='w-1/3 flex flex-row justify-end pr-10'>
          <button
            aria-label='notifications'
            className='flex flex-row items-center py-1 px-2 cursor-pointer'
          >
            <Image
              src={enableBell ? '/bell_on_icon.svg' : '/bell_off_icon.svg'}
              alt='Bell icon'
              width={24}
              height={24}
              onClick={() => setEnableBell(!enableBell)}
            />
          </button>

          <div className='h-8 border-r-2 border-black mx-3'></div>
          <button
            aria-label='settings'
            className='flex flex-row items-center py-1 pl-3 pr-10'
          >
            <Image
              src='/settings_icon.svg'
              alt='Login icon'
              width={24}
              height={24}
            />
            <div className='h-8 w-8 flex overflow-hidden rounded-full ml-6'>
              <Image
                src='/me_avatar.jpg'
                alt='avatar icon'
                width={500}
                height={617}
              />
            </div>

            <p className='ml-2 text-lg font-bold'>Fariz Akbar</p>
          </button>
        </div>
      </div>
      {/* navbar end */}
      {/* card */}

      <main className='w-full h-full  mb-10 p-3 flex flex-row'>
        {/* sidebar */}
        <Sidebar />
        {/* sidebar end */}
        {/* main content */}
        <div className='flex flex-col lg:flex-row h-full w-full sm:w-7/12 md:w-8/12 lg:w-9/12 xl:w-10/12  sm:px-10'>
          {/* todos */}
          <div
            className='h-full flex flex-col rounded-md shadow-lg bg-white w-full'
            style={{ maxWidth: '400px', maxHeight: '80vh' }}
          >
            <h1 className='font-bold text-xl m-5'>Todos</h1>
            <div className='h-full w-full flex flex-col overflow-y-scroll scrollbar pr-5'>
              {/* todo item */}

              {/* <div className='flex flex-row items-center mb-5 bg-black rounded-full p-2 ml-3'>
              <div className='h-14 w-14 bg-white rounded-full flex justify-center items-center'>
                <span className='font-bold text-xl text-black'>1</span>
              </div>
              <div className='flex flex-col ml-5 w-8/12 '>
                <p className='font-bold text-white'>Makan</p>

                <span className='font-semibold text-sm  text-white'>
                  08:00 - 09:00
                </span>
                <div className='w-full h-1 rounded-md bg-green-400'></div>
              </div>
              <button
                className='bg-transparent flex flex-row ml-1'
                aria-label='todo-menu'
              >
                <Image
                  src='/todo_menu_icon.svg'
                  alt='menu icon'
                  width={24}
                  height={24}
                />
              </button>
            </div> */}
              {todos.map((todo) => {
                return (
                  <div
                    className={`flex flex-col ${
                      selectedTodo.todoId === todo.id && selectedTodo.menuOpen
                        ? ''
                        : 'mb-5'
                    }`}
                    key={todo.id}
                  >
                    <div
                      className={`flex flex-row items-center w-full ${
                        selectedTodo.todoId === todo.id
                          ? ' black-background rounded-full p-2 ml-3'
                          : 'ml-5'
                      }`}
                    >
                      <div
                        className={`h-14 w-14 rounded-full flex justify-center items-center cursor-pointer ${
                          selectedTodo.todoId === todo.id
                            ? ' bg-white '
                            : ' black-background'
                        }`}
                        onClick={() =>
                          setSelectedTodo({
                            ...selectedTodo,
                            todoId: todo.id,
                          })
                        }
                      >
                        <span
                          className={`font-bold text-xl  ${
                            selectedTodo.todoId === todo.id
                              ? 'text-black'
                              : 'text-white'
                          }`}
                        >
                          {todo.id}
                        </span>
                      </div>
                      <div
                        className='flex flex-col ml-5 w-8/12 cursor-pointer'
                        onClick={() =>
                          setSelectedTodo({
                            ...selectedTodo,
                            todoId: todo.id,
                          })
                        }
                      >
                        <p
                          className={`font-bold ${
                            selectedTodo.todoId === todo.id ? 'text-white' : ''
                          }`}
                        >
                          Makan
                        </p>

                        <span
                          className={`font-semibold text-sm  ${
                            selectedTodo.todoId === todo.id
                              ? 'text-white'
                              : 'text-gray-600'
                          }`}
                        >
                          08:00 - 09:00
                        </span>
                        {selectedTodo.todoId === todo.id ? (
                          <div className='w-full h-1 rounded-md bg-green-400'></div>
                        ) : (
                          ''
                        )}
                      </div>
                      {selectedTodo.todoId === todo.id ? (
                        <button
                          className='bg-transparent flex flex-row ml-1 z-10'
                          aria-label='todo-menu'
                          onClick={() => {
                            setSelectedTodo({
                              todoId: todo.id,
                              menuOpen: !selectedTodo.menuOpen,
                            });
                            console.log('clicked');
                          }}
                        >
                          <Image
                            src='/todo_menu_icon.svg'
                            alt='menu icon'
                            width={24}
                            height={24}
                          />
                        </button>
                      ) : (
                        ''
                      )}
                    </div>
                    <div
                      className={`flex-row ml-12 mr-5 rounded-b-xl py-2 px-5 bg-gray-50 shadow-md justify-between shadow-gray-300 mb-5 ${
                        selectedTodo.todoId === todo.id && selectedTodo.menuOpen
                          ? 'flex'
                          : 'hidden'
                      }`}
                    >
                      <button
                        aria-label='edit-todo'
                        className='rounded-md px-3 black-background text-white font-semibold'
                      >
                        Edit
                      </button>
                      <button
                        aria-label='edit-todo'
                        className='rounded-md px-3 bg-red-400 text-white font-semibold'
                      >
                        Skip
                      </button>
                      <button
                        aria-label='edit-todo'
                        className='rounded-md px-3 bg-green-600 text-white font-semibold'
                      >
                        Save
                      </button>
                    </div>
                  </div>
                );
              })}

              {/* todo item end */}
            </div>
          </div>
          {/* todos end */}
          <div className='flex flex-row xl:flex-col justify-between xl:justify-start w-full px-3 md:px-10 pt-5 items-start'>
            <div className='flex flex-col items-center'>
              <h1 className='text-base lg:text-xl font-bold'>Jumlah task</h1>
              <div className='p-5 rounded-lg drop-shadow-md bg-white'>
                <span className='text-2xl lg:text-3xl font-bold'>
                  {todos.length}
                </span>
              </div>
            </div>

            <button
              className={`flex flex-row items-center py-1 px-3 mt-5 rounded-lg shadow-lg bg-white ml-5`}
            >
              <Image
                src='/publish_on_icon.svg'
                alt='Publish icon'
                width={24}
                height={24}
              />
              <p className={`ml-2 text-lg font-bold text-on-color`}>Publish</p>
            </button>
          </div>
        </div>
        {/* main content end */}
      </main>
      {/* card end */}
    </div>
  );
};

export default MyActivity;
