import React from 'react';
import { useState } from 'react';
import Image from 'next/image';
import Sidebar from '../components/Sidebar';
import Head from 'next/head';

const Profile = () => {
  const [enableBell, setEnableBell] = useState(false);
  const [showPasswordField, setShowPasswordField] = useState(false);

  return (
    <div className='h-screen w-full flex flex-col background-color px-10 font-sans'>
      <Head>
        {/* <html lang='en' /> */}
        <title>Profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* navbar */}
      <div className='w-full flex flex-row justify-between px-5 py-3'>
        <span>
          <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </span>
        <div className='w-1/3 flex flex-row justify-end pr-10'>
          <button
            aria-label='notifications'
            className='flex flex-row items-center py-1 px-2 cursor-pointer'
          >
            <Image
              src={enableBell ? '/bell_on_icon.svg' : '/bell_off_icon.svg'}
              alt='Bell icon'
              width={24}
              height={24}
              onClick={() => setEnableBell(!enableBell)}
            />
          </button>

          <div className='h-8 border-r-2 border-black mx-3'></div>
          <button
            aria-label='settings'
            className='flex flex-row items-center py-1 pl-3 pr-10'
          >
            <Image
              src='/settings_icon.svg'
              alt='Login icon'
              width={24}
              height={24}
            />
            <div className='h-8 w-8 flex overflow-hidden rounded-full ml-6'>
              <Image
                src='/me_avatar.jpg'
                alt='avatar icon'
                width={500}
                height={617}
              />
            </div>

            <p className='ml-2 text-lg font-bold'>Fariz Akbar</p>
          </button>
        </div>
      </div>
      {/* navbar end */}
      {/* card */}

      <main className='w-full h-full mb-10 p-3 flex flex-row'>
        {/* sidebar */}
        <Sidebar />
        {/* sidebar end */}
        {/* main content */}
        <div
          className='flex flex-col sm:w-7/12 md:w-8/12 lg:w-9/12 xl:w-10/12 px-10 overflow-y-scroll scrollbar pb-10'
          style={{ maxHeight: '85vh' }}
        >
          <h1 className='font-bold text-3xl'>Profile</h1>
          {/* user form */}
          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 grid-flow-row gap-4 mt-10 '>
            {/* user profile picture */}

            <div className='flex flex-col items-center'>
              <div className='border-4 border-white rounded-full overflow-hidden h-32 lg:h-44 w-32  lg:w-44'>
                <Image
                  src='/me_avatar.jpg'
                  width={200}
                  height={250}
                  alt='user-profile'
                  //   className='border-4 border-gray-400 rounded-full'
                />
              </div>
              <button
                className={`flex flex-row items-center py-1 px-3 mt-5 rounded-lg shadow-lg bg-white `}
              >
                <Image
                  src='/person_on_icon.svg'
                  alt='Person icon'
                  width={24}
                  height={24}
                />
                <p className={`ml-2 text-lg font-bold text-on-color`}>
                  Ganti foto
                </p>
              </button>
            </div>
            {/* user profile picture end */}
            <div className='flex flex-col items-start'>
              <input
                type='text'
                className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 mt-10'
                placeholder='Nama kamu'
              />
              <input
                type='text'
                className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 '
                placeholder='Email kamu'
              />
              {showPasswordField ? (
                <>
                  <input
                    type='password'
                    className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 '
                    placeholder='Password baru kamu'
                  />
                  <input
                    type='password'
                    className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 '
                    placeholder='Konfirmasi password'
                  />
                </>
              ) : (
                <button
                  className={`flex flex-row items-center py-1 px-3 mt-5 rounded-lg shadow-lg bg-white `}
                  onClick={() => setShowPasswordField(!showPasswordField)}
                >
                  <Image
                    src='/key_on_icon.svg'
                    alt='Password key icon'
                    width={24}
                    height={24}
                  />
                  <p className={`ml-2 text-lg font-bold text-on-color`}>
                    Ganti Password
                  </p>
                </button>
              )}
            </div>
            <div className='flex flex-col items-end'>
              <input
                type='text'
                className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 mt-10'
                placeholder='Profesi kamu'
              />
              <input
                type='text'
                className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 '
                placeholder='Jenis kelamin'
              />
              <input
                type='date'
                className='w-full shadow-xl input-field-radius  h-14 px-4 mb-5 '
                placeholder='Tanggal lahir'
              />
              <button
                className={`flex flex-row items-center py-1 px-3 mt-5 rounded-lg shadow-lg bg-white `}
              >
                <Image
                  src='/save_on_icon.svg'
                  alt='Save icon'
                  width={24}
                  height={24}
                />
                <p className={`ml-2 text-lg font-bold text-on-color`}>Simpan</p>
              </button>
            </div>
          </div>
          {/* user form end */}
        </div>
        {/* main content end */}
      </main>
      {/* card end */}
    </div>
  );
};

export default Profile;
